### ISSUE TITLE
UX - SSW Mega Menu - Add hoverIntent 

### ISSUE THREAD

**Issue by piers-sinclair** [SSWConsulting/SSW.MegaMenu#2]
@tiagov8 @bradystroud @adamcogan
Hi Seb,

As per our conversation, I’d like to add hoverIntent to our mega menu: https://briancherne.github.io/jquery-hoverIntent/

A notice the dropdown menu pops up immediately every time the mouse passes over it which in many cases is not what the user wants

Please action
Cheers,
Tiago

**Comment by wicksipedia** [comment]
closing this as the megamenu now requires a click to open up a menu
