### ISSUE TITLE
Mobile Menu - Redundant submenu items

### ISSUE THREAD

**Issue by jaydenalchin** [SSWConsulting/SSW.MegaMenu#4]
CC: @UlyssesMaclaren 
Related PBI: https://ssw.visualstudio.com/SSW.Design/_workitems/edit/61510 

As per my conversation with @bradystroud:
**On mobile**, every item under "Services" on the menu sends the user to the same Consulting page, with the exception of "Book Now". This is also an issue with the "Training" submenu and the suggestions made below should also be applied there. 

1. Remove the redundant Services submenu on mobile
2. Make the "Services" megamenu item link to the consulting page itself 
3. Add the "Book Now" submenu item to the mobile megamenu, above "Services" 

![image](https://user-images.githubusercontent.com/75593567/118740697-d8ad4400-b88f-11eb-9784-f67391b99500.png)
**Figure: 6 submenu items that link to the same page**

![image](https://user-images.githubusercontent.com/75593567/118741564-d64be980-b891-11eb-9bb1-bd77928db8f9.png)
**Figure: Move Book Now to the top of the mobile menu here**

**Comment by wicksipedia** [comment]
Hey @jaydenalchin is this issue still applicable to the new megamenu?

If not, please close this issue
