### ISSUE TITLE
Mobile - Issue loading menu 

### ISSUE THREAD

**Issue by jaydenalchin** [SSWConsulting/SSW.MegaMenu#5]
Hi @bradystroud
As per our conversation, there seems to be some issue with the menu loading in on mobile. It looks like opening the mobile menu can sometimes cause it to push everything off-screen when it slides in. The screenshot below was taken on the page: https://www.ssw.com.au/ssw/Consulting/Consulting.aspx 

![image](https://user-images.githubusercontent.com/75593567/118743363-91c24d00-b895-11eb-9674-11d524d704bb.png)
**Figure: Mobile menu pushing everything away 😥**

**Comment by wicksipedia** [comment]
Hey @jaydenalchin - with the new megamenu is this still an issue?
