### ISSUE TITLE
🐛  Megamenu links always use anchors instead of client side routing

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.MegaMenu#59]
Cc: @jeoffreyfischer 

When I click on a link on the ssw website, it uses next/link to render the page which is fast.
When I click on a link in the megamenu, it grabs the html and does a full page load (slower).

It would be better if the megamenu used next/link on the website (where applicable) to have faster page loads

https://github.com/SSWConsulting/SSW.MegaMenu/assets/600044/493df1b4-975d-43e3-a532-4655a36a6bcf

**Comment by Harry-Ross** [comment]
FYI whoever works on this, I laid the groundwork for this by creating a `<CustomLink>` component everywhere an anchor tag was used, which means it would be easy to switch out for Next.js or Gatsby link components.
