### ISSUE TITLE
🐛 Cmd + K Search | Has an Outline and Redirects to Google

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.MegaMenu#65]
Cc:

Hi @BrookJeynes 

### Describe the Bug

We have Cmd+K in Rules now, that's SO COOL ⭐️

1. Find out who did that and say Good Job :)

BUT there's some issues.
- The resulting search bar has an outline
- The resulting search currently uses Google, when we finally have a cool search page
- Also has an actual Search button on it, which feels weird (Other things that have Cmd+K don't do this. E.g. Tailwind)

### To Reproduce
1. Go to ssw.rules
2. Press Cmd+K 
3. See the focus outline on the input.
4. Search for something
5. See that we land on Google.

### Expected Behavior

We should be using our own Search page on this one.

### Tasks
- [ ] Investigate
- [ ] Fix

Macbook M2 Pro
Arc Browser, Chromium

### Screenshots

![image](https://github.com/SSWConsulting/SSW.Rules/assets/17246482/e5aea456-e838-425e-b947-7d5ccc347278)

![image](https://github.com/SSWConsulting/SSW.Rules/assets/17246482/b740a4e3-604f-46a8-ad7c-e2e82590f165)

Thanks!

**Comment by BrookJeynes** [comment]
Moving to the MegaMenu repo as the cmd+k search component is stored here.

**Comment by BrookJeynes** [comment]
Closing as the rules cmd+k search now utilizes the search built into rules
